<? $this->headScript()->prependFile($this->baseUrl(). "/module/mazelab/nginx/js/codemirror/mode/nginx.js"); ?>
<? $this->headScript()->prependFile($this->baseUrl(). "/module/mazelab/nginx/js/codemirror/codemirror.js"); ?>
<? $this->headLink()->prependStylesheet($this->baseUrl(). "/module/mazelab/nginx/css/codemirror/codemirror.css"); ?>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid text-left cssBoxCenter">
            <a href="<?= $this->url(array($this->html("vhost/_id")), "mazelab-nginx_deleteVhost") ?>"
               class="jsDelete btn" title="<?= $this->translate('delete Vhost') ?>">
                <i class="icon-trash"></i>
                <?= $this->translate("delete"); ?>
            </a>
            <a <?= !$this->toBool("vhost/status") ? "style=\"display:none;\"" : null; ?>
                href="<?= $this->url(array($this->html("vhost/_id")), "mazelab-nginx_deactivateVhost") ?>"
                class="jsChangeState btn" title="<?= $this->translate('deactivate') ?>">
                <i class="icon-ok-sign"></i>
                <?= $this->translate('deactivate') ?>
            </a>
            <a <?= $this->toBool("vhost/status") ? "style=\"display:none;\"" : null; ?>
                href="<?= $this->url(array($this->html("vhost/_id")), "mazelab-nginx_activateVhost") ?>"
                class="jsChangeState btn inactive" title="<?= $this->translate('activate') ?>">
                <i class="icon-minus-sign"></i>
                <?= $this->translate('activate'); ?>
            </a>
        </div>
        <div class="row-fluid text-right cssStatusText cssBigItem">
            <span <?= !$this->toBool("vhost/status") ? "style=\"display:none;\"" : null; ?>
                class="span11 jsVhostStatus stat online">
                online
            </span>
            <span <?= $this->toBool("vhost/status") ? "style=\"display:none;\"" : null; ?>
                class="span11 jsVhostStatus stat offline">
                offline
            </span>
        </div>
        <div class="row-fluid">
            <div class="span10">
                <div class="row-fluid">
                    <div class="cssUserImage span2">
                        <img class="img-polaroid" id="jsImageNodeType" name="avatar" src="<?= $this->baseUrl() ?>/img/dummy_node_200.png" alt="<?= $this->translate('avatar') ?>">
                    </div>
                    <div class="span9 offset1 cssBoxCenter">
                        <form action="<?= $this->url(array($this->html('node/name')), 'nodedetail') ?>" method="post">
                            <dl class="row-fluid cssBigItem">
                                <span class="span9">
                                    <?= $this->html("vhost/label") ; ?>
                                </span>
                            </dl>
                            <dl class="row-fluid">
                                <dt class="span3">
                                <label id="nodetype">
                                    <?= $this->form->nodeId->getLabel(); ?>
                                </label>
                                </dt>
                                <dd class="span9">
                                    <?= $this->form->nodeId ?>
                                    <input class="btn btn-info" id="buttonSaveNodeChanges" type="button" value="<?= $this->translate('ok'); ?>"> 
                                </dd>
                            </dl>
                            <? if ($this->toBool('vhost/domainId')): ?>
                            <dl class="row-fluid">
                                <dt class="span3">
                                <label id="nodetype">
                                    <?= $this->form->domainId->getLabel(); ?>
                                </label>
                                </dt>
                                <dd class="span9">
                                    <?= $this->form->domainId; ?>
                                </dd>
                            </dl>
                            <? endif; ?>
                        </form>
                    </div>
                </div>
                <div class="row-fluid">
                    <dl class="row-fluid cssBoxCenter">
                        <dt class="span3">
                            <pre class="cssNginxCode">
<?= $this->translate('Example:'); ?> 

server {
    listen 8080;
    server_name <?= $this->toBool("vhost/domainName") ? $this->html("vhost/domainName") : "test.xy" ?>;

    root /var/www;

    # comment
}


</pre>
                            <input id="jsCancelButton" class="btn btn-info" type="reset" value="<?= $this->translate('cancel') ?>" />
                            <input class="btn btn-info jsButton" id="jsSaveVhost" type="submit" value="<?= $this->translate('save') ?>" />
                        </dt>
                        <dd class="span9">
                            <?= $this->form->content; ?>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
    <div id="jsConfirmDeleteVhost" class="modal hide fade">
        <div class="modal-body">
            <p><?= $this->translate('Shall the Vhost really be deleted?'); ?></p>
        </div>
        <div class="modal-footer">
            <a class="btn jsButtonCancel" data-dismiss="modal"><?= $this->translate('cancel'); ?></a>
            <a class="btn btn-primary jsButtonDelete" data-dismiss="modal"><?= $this->translate('ok'); ?></a>
        </div>
    </div>
</div>

<script type="text/javascript">
    var nginxConf = CodeMirror.fromTextArea(document.getElementById("content"), {mode: "nginx"});
    
    $(document).ready(function() {
        $("#jsCancelButton").click(function() {
            history.back();
        });

        $("#jsSaveVhost").click(function() {
            if (nginxConf.getValue() === $("#content").text()) {
                return false;
            }

            resetMessages();
            $.ajax({
                url : "<?= $this->url(array(), "mazelab-nginx_editVhost") ?>?format=json",
                type: "post",
                data: {content: nginxConf.getValue()},
                success: function(data) {
                    if (typeof data !== "object" || data.result !== true) {
                        setErrorMessages(["<?= $this->translate('Vhost %1$s konnte nicht gespeichert werden', $this->translate("Content")); ?>"]);
                    }
                },
                complete: function(xhr) {
                    setMessages(xhr.responseText);
                }
            });

            return false;
        });

        $(".jsChangeState").click(function(){
            resetMessages();
            self = $(this).addClass("disabled");

            !self.data("locked") && $.ajax({
                url: this.href,
                data: {format: "json"},
                success:function(data){
                    if (data.result === true){
                        $(".jsChangeState").toggle();
                        $(".jsVhostStatus").toggle();
                    }

                    setMessages(data);
                },
                complete:function(){
                    self.removeClass("disabled").data("locked", false);
                }
            });
            self.data("locked", true);

            return false;
        });

        $('#buttonSaveNodeChanges').click(function() {
            $.ajax({
                url: '<?= $this->url(array(), 'mazelab-nginx_editVhost') ?>?format=json',
                type: "post",
                data: $('#nodeId').serialize(),
                success: function(data) {
                    if (!$.isEmptyObject(data.formErrors)){
                        setErrorTooltip(data.formErrors);
                        setTimeout(function(){
                            resetTooltips();
                        }, 4000);
                    }

                    setMessages(data, true);
                }
            });
            return false;
        });

        $(".jsDelete").click(function(){
            self = $(this);
            var dialog = $("#jsConfirmDeleteVhost").modal({backdrop:"static", show:true});
            dialog.find(".jsButtonDelete").unbind("click").click(function(){
            $.ajax({
                url: self.attr("href"),
                data: {format: "json"},
                success:function(data){
                    if (data.result === true){
                        location.href = "<?= $this->url(array(), "mazelab-nginx_vhosts") ?>";
                    }
                    setMessages(data);
                }
            });
                dialog.modal("hide");
            }).andSelf().find(".jsButtonCancel").click(function(){
                dialog.modal("hide");
            });
            return false;
        });
    });
</script>