<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid cssListing span2">
            <div class="span12 cssHeaderList">
                <div class="cssButton span12">
                    <a class="btn btn-info jsButton" href="<?= $this->url(array(), 'mazelab-nginx_addVhost');  ?>">
                        <?= $this->translate("New vhost") ?>
                    </a>
                </div>
            </div>
        </div>
        
        <?= $this->render('vhosts/pager.phtml') ?>

        <div id="listVhosts" class="row-fluid cssListing">
            <ul class="span12 unstyled">
                <li class="row-fluid">
                    <div class="offset10 span2 cssAction"></div>
                </li>

                <? foreach ($this->html("pager/data") as $id => $vhost): ?>
                <li class="row-fluid">
                    <div class="span12
                    <? if($vhost->toBool('delete')): ?>
                        cssStatusDelete
                    <? elseif($vhost->toBool('conflicted')): ?>
                        cssStatusConflicted
                    <? elseif($vhost->toBool('pending')): ?>
                        cssStatusPending
                    <? endif; ?>
                        ">
                        <? if($vhost->toBool('delete')): ?>
                        <span class="cssListItem span12">
                        <? else: ?>
                        <a class="cssListItem span12" title="<?= $this->translate("detail") ?>"
                            href="<?= $this->url(array($id), "mazelab-nginx_editVhost") ?>">
                        <? endif; ?>
                            <span class="cssAvatar">
                               <img src="<?= $this->baseUrl() ?>/img/dummy_node_50.png" alt="<?= $this->translate('avatar') ?>"/>
                           </span>
                            <span>
                                <?= $vhost->html('label'); ?>
                            </span>
                            <? if($vhost->toBool('domainName')): ?>
                            <span>
                                <?= $this->translate('of domain %1$s', $vhost->html('domainName')); ?>
                            </span>
                            <? endif;?>
                            <? if($vhost->toBool('nodeName')): ?>
                            <span>
                                <?= $this->translate('on node %1$s', $vhost->html('nodeName')); ?>
                            </span>
                            <? if($vhost->toBool('pending') || $vhost->toBool('delete')): ?>
                            <span class="icon-refresh cssStatusIconPending"></span>
                            <? endif; ?>
                            <? endif;?>
                        <? if($vhost->toBool('delete')): ?>
                        </span>
                        <? else: ?>
                        </a>
                        <? endif; ?>
                    </div>
                </li>
                <? endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#nginxVhostSearch').mazeSearch({
            source: '<?= $this->url(array(), 'mazelab-nginx_vhosts') ?>?format=html',
            limit: '<?= $this->html('pager/limit') ?>',
            total: '<?= $this->html('pager/total') ?>',
            page: '<?= $this->html('pager/page') ?>',
            lastPosition: '<?= $this->html('pager/lastPosition') ?>',
            term: '<?= $this->html('pager/searchTerm') ?>'
        });
        
        $('#jsPagerNext').unbind("click").click(function() {
            $('#nginxVhostSearch').mazeSearch('next');
            return false;
        });

        $('#jsPagerPrev').unbind("click").click(function() {
            $('#nginxVhostSearch').mazeSearch('prev');
            return false;
        });

        $('.jsPagerFirst').unbind("click").click(function() {
            $('#nginxVhostSearch').mazeSearch('first');
            return false;
        });

        $('.jsPagerLast').unbind("click").click(function() {
            $('#nginxVhostSearch').mazeSearch('last');
            return false;
        });
    });
</script>
